### ISSUE TITLE
want some data preprocess code

### ISSUE THREAD

**Issue by clarkliucs** [solidaqua/LSTM-timit#1]
hello!
 i am trying to reproduce your work, in the progress, i found some problems confusing me. in the timit dataset, its max labels in a sequence is 78, and the frames are usually 600 or 700. how do you match these frames and labels?
 can you give some preprocess code on timit dataset? i want to know the data structure in "timit_reduced_mfcc.h5". thank you very much!

**Comment by gevangelopoulos** [comment]
Hello, 
Please see this [gist](https://gist.github.com/Qwlouse/3d33c8529f446b9fc5c0) in order to preprocess the timit h.5 file. You can also open h5 files with graphical tools, you can find them with a quick search.
Finally, the frames are usually 600-700 because they represent audio of 25ms shifted by 10ms. The labels in the timit dataset are accompanied with a file that represents the duration of each label. In the script, this data is expanded and each frame of the 600-700 gets one label so you get the sequence of MFCCs which might be lets say 600x39 and the sequence of the labels 600x1. Then you can do classification with any algorithm or architecture you prefer.
